### ISSUE TITLE
ProfileConfigurator: throws error in Interactive Book

### ISSUE THREAD

**Issue by patrickfrohmann** [codefluegel/h5p-modelviewer#8]

**Comment by patrickfrohmann** [comment]
![Image](https://github.com/user-attachments/assets/981a82dd-4bbd-4fab-85b4-5ec6386fc333)

**Comment by otacke** [comment]
@patrickfrohmann The issue occurred only if the author had not added any choices. The H5P question type contract then would cause functions to be called that expected choices to be present. Fixed in https://github.com/codefluegel/h5p-profile-configurator-xr/pull/1
